title: Leedeo Studio
email: javo@leedeo.studio
description: >-
  Recursos y formación para creadores de videojuegos. Tutoriales prácticos de Godot Engine, diseño con Affinity y consejos de visibilidad para tus proyectos.
baseurl: ""
url: "https://leedeo.github.io"
twitter_username: leedeostudio
github_username:  Leedeo

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

future: true
timezone: Europe/Madrid

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
