title: Leedeo Studio
email: javo@leedeo.studio
description: >-
  Leedeo Studio: Tutoriales prácticos de Godot Engine, cursos de desarrollo de videojuegos y herramientas exclusivas de optimización como Leedeo Cleaner.
baseurl: ""
url: "https://leedeo.github.io"
permalink: /blog/:year/:month/:day/:title/
twitter_username: leedeostudio
github_username:  Leedeo

social:
  name: "Leedeo Studio"
  links:
    - https://www.youtube.com/leedeo
    - https://x.com/leedeostudio
    - https://github.com/Leedeo
    - https://ko-fi.com/leedeo

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 12
paginate_path: "/blog/page:num/"

future: true
timezone: Europe/Madrid

# Disqus Comments
disqus_shortname: "leedeo"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - assets/css/tailwind-input.css
